# Generated by Django 4.2.29 on 2026-04-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geofence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alarm_type",
                    models.CharField(
                        choices=[
                            ("geofence_enter", "위험구역 진입"),
                            ("sensor_caution", "센서 주의"),
                            ("sensor_danger", "센서 위험"),
                            ("combined", "복합 위험"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "alarm_level",
                    models.CharField(
                        choices=[
                            ("info", "정보"),
                            ("caution", "주의"),
                            ("danger", "위험"),
                            ("critical", "심각"),
                        ],
                        default="caution",
                        max_length=20,
                    ),
                ),
                ("worker_id", models.CharField(blank=True, default="", max_length=50)),
                (
                    "worker_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("worker_x", models.FloatField(blank=True, null=True)),
                ("worker_y", models.FloatField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, default="", max_length=50)),
                (
                    "sensor_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "geofence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarms",
                        to="geofence.geofence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
