# Generated by Django 4.2.29 on 2026-05-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="feedback",
            field=models.CharField(
                blank=True,
                choices=[("tp", "정탐"), ("fp", "오탐")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="feedback_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alarm",
            name="alarm_type",
            field=models.CharField(
                choices=[
                    ("geofence_enter", "위험구역 진입"),
                    ("sensor_caution", "센서 주의"),
                    ("sensor_danger", "센서 위험"),
                    ("combined", "복합 위험"),
                    ("ai_anomaly_warning", "AI 통계 이상"),
                    ("ai_trend_shift", "AI 급변 탐지"),
                    ("ai_ml_anomaly", "AI ML 이상"),
                    ("ai_predictive_warning", "AI 예측 주의"),
                    ("ai_predictive_alert", "AI 예측 위험"),
                    ("ai_drift_alert", "AI 드리프트 탐지"),
                    ("ai_correlation", "AI 상관관계 이상"),
                ],
                max_length=30,
            ),
        ),
    ]
