# Generated by Django 4.2.29 on 2026-04-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarm_type',
            field=models.CharField(choices=[('zone_enter', '구역 진입'), ('zone_exit', '구역 이탈'), ('state_caution_enter', '주의 진입'), ('state_danger_enter', '위험 진입'), ('state_escalate', '상태 악화'), ('state_recover_partial', '부분 회복'), ('state_recover_safe', '안전 복귀'), ('state_ongoing', '상태 지속'), ('sensor_caution', '센서 주의'), ('sensor_danger', '센서 위험'), ('sensor_recover_partial', '센서 부분 회복'), ('sensor_recover_normal', '센서 정상 복귀')], max_length=30),
        ),
    ]
