# Generated by Django 4.2.29 on 2026-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="is_ai",
            field=models.BooleanField(default=False),
        ),
    ]
