# Generated by Django 4.2.29 on 2026-05-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alarm_feedback_alarm_feedback_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alarm",
            index=models.Index(fields=["-created_at"], name="alarm_created_idx"),
        ),
        migrations.AddIndex(
            model_name="alarm",
            index=models.Index(
                fields=["alarm_type", "-created_at"], name="alarm_type_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alarm",
            index=models.Index(
                fields=["device_id", "alarm_type", "created_at"],
                name="alarm_device_type_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alarm",
            index=models.Index(
                fields=["is_read", "-created_at"], name="alarm_read_created_idx"
            ),
        ),
    ]
