# Generated by Django 4.2.29 on 2026-05-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alarm_is_ai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="alarm_type",
            field=models.CharField(
                choices=[
                    ("geofence_enter", "위험구역 진입"),
                    ("sensor_caution", "센서 주의"),
                    ("sensor_danger", "센서 위험"),
                    ("combined", "복합 위험"),
                    ("ai_prediction", "AI 예측"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AIPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=50)),
                ("sensor_key", models.CharField(max_length=20)),
                ("sensor_type", models.CharField(max_length=20)),
                ("value_at_predict", models.FloatField()),
                ("threshold", models.FloatField()),
                ("slope", models.FloatField()),
                ("if_score", models.FloatField()),
                ("predicted_ticks", models.IntegerField()),
                ("predicted_value", models.FloatField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "검증 중"),
                            ("success", "예측 성공"),
                            ("failure", "예측 실패"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alarm",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_prediction",
                        to="alerts.alarm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device_id", "sensor_key", "result"],
                        name="alerts_aipr_device__890fae_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="alerts_aipr_expires_c4406b_idx"
                    ),
                ],
            },
        ),
    ]
