# Generated by Django 4.2.29 on 2026-05-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_ai_alarm_types_feedback_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='feedback_at',
        ),
    ]
