# Generated by Django 4.2.29 on 2026-05-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_add_missing_alarm_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarm_type',
            field=models.CharField(choices=[('geofence_enter', '위험구역 진입'), ('combined', '복합 위험'), ('sensor_caution', '센서 주의'), ('sensor_danger', '센서 위험'), ('sensor_ongoing', '센서 지속 중'), ('sensor_recover_partial', '센서 부분 회복'), ('sensor_recover_normal', '센서 정상 회복'), ('state_caution_enter', '작업자 주의'), ('state_danger_enter', '작업자 위험'), ('state_escalate', '상태 에스컬레이션'), ('state_ongoing', '상태 지속 중'), ('state_recover_partial', '부분 회복'), ('state_recover_safe', '완전 회복'), ('ai_prediction', 'AI 예측'), ('ai_anomaly_warning', 'AI 통계 이상'), ('ai_trend_shift', 'AI 급변 탐지'), ('ai_ml_anomaly', 'AI ML 이상'), ('ai_predictive_warning', 'AI 예측 주의'), ('ai_predictive_alert', 'AI 예측 위험'), ('ai_drift_alert', 'AI 드리프트 탐지'), ('ai_correlation', 'AI 상관관계 이상')], max_length=30),
        ),
    ]
