# Generated by Django 4.2.29 on 2026-05-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_add_sensor_ongoing_alarm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='related_device_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
