# Generated by Django 4.2.29 on 2026-04-24 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VRTrainingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_date", models.DateField(verbose_name="교육 날짜")),
                (
                    "last_position_sec",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="이탈 시 저장되는 시청 지점. 다음 진입 시 여기서 재생 재개.",
                        verbose_name="마지막 재생 위치 (초)",
                    ),
                ),
                (
                    "total_duration_sec",
                    models.PositiveIntegerField(
                        default=0, verbose_name="영상 총 길이 (초)"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시각"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="최초 진입 시각"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="마지막 갱신 시각"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vr_training_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "VR 교육 이력",
                "verbose_name_plural": "VR 교육 이력 목록",
                "db_table": "vr_training_log",
                "ordering": ["-check_date", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-check_date"],
                        name="vr_training_user_id_c9865d_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="vrtraininglog",
            constraint=models.UniqueConstraint(
                fields=("user", "check_date"), name="uniq_vr_training_per_user_per_day"
            ),
        ),
    ]
