# Generated by Django 4.2.29 on 2026-04-24 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="email",
            field=models.EmailField(
                blank=True, default="", help_text="이메일", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="마지막 heartbeat 시각. WorkerLocation 가 들어올 때마다 갱신되어 '연결 상태' 판정에 쓰임.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="phone",
            field=models.CharField(
                blank=True, default="", help_text="연락처", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="position",
            field=models.CharField(
                blank=True,
                default="",
                help_text="직급 (사원/대리/과장 등)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="workerlocation",
            name="movement_status",
            field=models.CharField(
                choices=[("moving", "이동"), ("stationary", "정지")],
                default="moving",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_type",
                    models.CharField(
                        choices=[
                            ("single", "개별"),
                            ("selected", "선택"),
                            ("all", "전체"),
                        ],
                        help_text="전송 유형",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="메시지 본문 (최대 100자 권장)", max_length=200
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipients",
                    models.ManyToManyField(
                        help_text="수신 대상 작업자 (스냅샷)",
                        related_name="received_notifications",
                        to="workers.worker",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="알림을 보낸 관리자 (로그인 사용자)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "알림 전송 이력",
                "verbose_name_plural": "알림 전송 이력 목록",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["-sent_at"], name="workers_not_sent_at_eef6ad_idx"
                    )
                ],
            },
        ),
    ]
