# Generated by Django 4.2.29 on 2026-04-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True,
                default="",
                help_text="사원 / 대리 / 과장 / 팀장 등",
                max_length=50,
                verbose_name="직급",
            ),
        ),
    ]
