# Generated by Django 4.2.29 on 2026-04-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="o2",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
