# Generated by Django 4.2.29 on 2026-04-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_sensordata_o2"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="nh3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="no2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="o3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="so2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="voc",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
