# Generated by Django 4.2.29 on 2026-04-21 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geofence", "0001_initial"),
        ("devices", "0003_sensordata_nh3_sensordata_no2_sensordata_o3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="geofence",
            field=models.ForeignKey(
                blank=True,
                help_text="이 센서가 속한 지오펜스 (없으면 공용 구역)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="geofence.geofence",
            ),
        ),
    ]
