# Generated by Django 4.2.29 on 2026-04-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geofence", "0001_initial"),
        ("devices", "0003_device_geofence_sensordata_nh3_sensordata_no2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="geofence",
            field=models.ForeignKey(
                blank=True,
                help_text="이 센서가 속한 지오펜스 (없으면 공용 구역)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="geofence.geofence",
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="co",
            field=models.FloatField(
                blank=True, help_text="일산화탄소 (ppm)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="co2",
            field=models.FloatField(
                blank=True, help_text="이산화탄소 (ppm)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="h2s",
            field=models.FloatField(blank=True, help_text="황화수소 (ppm)", null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="nh3",
            field=models.FloatField(blank=True, help_text="암모니아 (ppm)", null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="no2",
            field=models.FloatField(
                blank=True, help_text="이산화질소 (ppm)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="o2",
            field=models.FloatField(
                blank=True, help_text="산소 (%), 구간형 판정", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="o3",
            field=models.FloatField(blank=True, help_text="오존 (ppm)", null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="so2",
            field=models.FloatField(blank=True, help_text="이산화황 (ppm)", null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="voc",
            field=models.FloatField(
                blank=True, help_text="유기화합물 (ppm)", null=True
            ),
        ),
    ]
