# Generated by Django 4.2.29 on 2026-04-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_device_geofence"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="voltage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="watt",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
