# Generated by Django 4.2.29 on 2026-04-24 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_sensordata_current_sensordata_voltage_and_more'),
        ('devices', '0005_sensordata_power_fields'),
    ]

    operations = [
    ]
