# Generated by Django 6.0.4 on 2026-04-20 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(
                        help_text="작업자 식별자 (worker_01 등)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="작업자명", max_length=100)),
                (
                    "department",
                    models.CharField(
                        blank=True, default="", help_text="소속 부서", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="활성 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "작업자",
                "verbose_name_plural": "작업자 목록",
                "ordering": ["worker_id"],
            },
        ),
        migrations.CreateModel(
            name="WorkerLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField(help_text="평면도 X 좌표")),
                ("y", models.FloatField(help_text="평면도 Y 좌표")),
                (
                    "movement_status",
                    models.CharField(
                        choices=[("moving", "이동"), ("stationary", "정지")],
                        default="moving",
                        help_text="이동 상태",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        help_text="소속 작업자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="workers.worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "작업자 위치",
                "verbose_name_plural": "작업자 위치 이력",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["worker", "-timestamp"],
                        name="workers_wor_worker__bf6a09_idx",
                    )
                ],
            },
        ),
    ]
