# Generated by Django 4.2.29 on 2026-04-27 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backoffice', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, default='', help_text='001, 002 ... 같은 식별 코드 (피그마 디자인)', max_length=50, verbose_name='부서 코드'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_unassigned_bucket',
            field=models.BooleanField(default=False, help_text='True 인 단일 노드가 부서 미지정 사용자의 자동 소속처', verbose_name='조직 없음 버킷 여부'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='해당 부서의 조직장 (구성원 중 1명)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_organizations', to=settings.AUTH_USER_MODEL, verbose_name='조직장'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='회사명 또는 부서명', max_length=100, verbose_name='조직명'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='None 이면 회사(root)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backoffice.organization', verbose_name='상위 조직'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False 면 신규 사용자 등록 시 선택 목록에서 제외', verbose_name='사용 여부'),
        ),
        migrations.AlterField(
            model_name='position',
            name='sort_order',
            field=models.IntegerField(default=100, help_text='작을수록 상위 직위 (대표이사=1)', verbose_name='정렬 순서'),
        ),
    ]
