# Generated by Django 4.2.29 on 2026-04-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mapimage",
            options={"ordering": ["sort_order", "uploaded_at"]},
        ),
        migrations.AddField(
            model_name="mapimage",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="페이지네이션 순서 (작은 값이 먼저)"
            ),
        ),
    ]
