# Generated by Django 4.2.29 on 2026-04-22 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geofence", "0001_initial"),
        ("devices", "0002_sensordata_o2"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="geofence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="geofence.geofence",
            ),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="nh3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="no2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="o3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="so2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="voc",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
