# Generated by Django 4.2.29 on 2026-04-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_device_geofence_alter_sensordata_co_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="current",
            field=models.FloatField(blank=True, help_text="전류 (A)", null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="voltage",
            field=models.FloatField(blank=True, help_text="전압 (V)", null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="watt",
            field=models.FloatField(blank=True, help_text="전력 (W)", null=True),
        ),
    ]
