# Generated by Django 4.2.29 on 2026-04-24 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_date",
                    models.DateField(
                        help_text="YYYY-MM-DD. 해당 날짜의 작업 전 점검 1회 기록",
                        verbose_name="점검 날짜",
                    ),
                ),
                (
                    "checked_items",
                    models.JSONField(
                        default=list,
                        help_text='["1_1", "1_2", ...] 형태. checklist_data.CHECKLIST_ITEMS 의 item.key',
                        verbose_name="체크된 항목 목록",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="최초 완료 시각"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최근 수정 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_checklists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "안전 확인 체크리스트",
                "verbose_name_plural": "안전 확인 체크리스트 목록",
                "db_table": "safety_checklist",
                "ordering": ["-check_date", "-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-check_date"],
                        name="safety_chec_user_id_8e5096_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="safetychecklist",
            constraint=models.UniqueConstraint(
                fields=("user", "check_date"),
                name="uniq_safety_checklist_per_user_per_day",
            ),
        ),
    ]
