# Generated by Django 4.2.29 on 2026-04-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeoFence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("danger", "위험"),
                            ("caution", "주의"),
                            ("restricted", "출입금지"),
                        ],
                        default="danger",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("medium", "보통"),
                            ("high", "높음"),
                            ("critical", "심각"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                ("polygon", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
