# Generated by Django 4.2.29 on 2026-04-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofence',
            name='zone_type',
            field=models.CharField(choices=[('open', '개방구역'), ('monitored', '상시감시'), ('hazardous', '유해구역'), ('restricted', '출입금지')], default='open', max_length=20),
        ),
    ]
