# Generated by Django 4.2.29 on 2026-04-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geofence", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geofence",
            name="risk_level",
        ),
    ]
