# Generated by Django 4.2.29 on 2026-05-12 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_sensordata_current_sensordata_voltage_and_more"),
        ("geofence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geofence",
            name="confirmed_devices",
            field=models.ManyToManyField(
                blank=True,
                help_text="확산 확인된 인접 센서들 (Tier 2/3 승격 근거)",
                related_name="confirmed_in_zones",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="current_radius_px",
            field=models.FloatField(
                blank=True,
                help_text="그레이엄 기반 현재 이론 반경 (동적 zone 만)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="자동 만료 시각 (동적 zone)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="gas_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="확산 계산용 가스 종류 (co, h2s, co2, ...)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="is_dynamic",
            field=models.BooleanField(
                db_index=True, default=False, help_text="동적으로 자동 생성된 zone 여부"
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="last_updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="마지막 갱신 (반경 진화, tier 승격 등)"
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="source_device",
            field=models.ForeignKey(
                blank=True,
                help_text="동적 zone 발동 센서 (정적 zone 은 null)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_zones",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— (정적)"),
                    ("tentative", "잠정"),
                    ("confirmed", "확인됨"),
                    ("critical", "긴급"),
                ],
                default="",
                help_text="동적 zone 신뢰도 단계",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="geofence",
            name="trigger_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— (정적)"),
                    ("manual", "관리자 지정"),
                    ("threshold", "임계 초과"),
                    ("ttm_anomaly", "TTM 이상 탐지"),
                    ("ttm_forecast", "TTM 사전 경고"),
                ],
                default="",
                help_text="동적 zone 발동 원인",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="geofence",
            index=models.Index(
                fields=["is_active", "is_dynamic"],
                name="geofence_ge_is_acti_317189_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geofence",
            index=models.Index(
                fields=["source_device", "is_active"],
                name="geofence_ge_source__fedfb8_idx",
            ),
        ),
    ]
