# Generated by Django 4.2.29 on 2026-05-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geofence", "0002_geofence_confirmed_devices_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Zone 생성"),
                            ("polygon_expanded", "Polygon 확장 (이웃 추가)"),
                            ("upgraded_to_confirmed", "Tier 승격 → 확인됨"),
                            ("upgraded_to_critical", "Tier 승격 → 긴급"),
                            ("expired", "Zone 만료"),
                        ],
                        max_length=30,
                    ),
                ),
                ("from_tier", models.CharField(blank=True, default="", max_length=20)),
                ("to_tier", models.CharField(blank=True, default="", max_length=20)),
                (
                    "trigger_source",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="geofence.geofence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["zone", "created_at"],
                        name="geofence_zo_zone_id_4e5c01_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="geofence_zo_event_t_4512c4_idx",
                    ),
                ],
            },
        ),
    ]
