# Generated by Django 4.2.29 on 2026-04-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geofence", "0002_remove_geofence_risk_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="geofence",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "낮음"),
                    ("medium", "보통"),
                    ("high", "높음"),
                    ("critical", "심각"),
                ],
                default="high",
                max_length=20,
            ),
        ),
    ]
