# Generated by Django 4.2.29 on 2026-04-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofence', '0002_alter_geofence_zone_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geofence',
            name='risk_level',
        ),
    ]
