# Generated by Django 4.2.29 on 2026-05-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofence', '0003_zoneevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofence',
            name='trigger_source',
            field=models.CharField(blank=True, choices=[('', '— (정적)'), ('manual', '관리자 지정'), ('threshold', '임계 초과'), ('ttm_anomaly', 'TTM 이상 탐지'), ('ttm_forecast', 'TTM 사전 경고'), ('scenario_op_op_single', '단일 누출 시나리오'), ('scenario_op_op_multi', '다중 누출 시나리오'), ('scenario_op_op_h2s', 'H2S 누출 시나리오')], default='', help_text='동적 zone 발동 원인', max_length=40),
        ),
        migrations.AlterField(
            model_name='geofence',
            name='zone_type',
            field=models.CharField(choices=[('normal', '정상'), ('caution', '주의'), ('danger', '위험'), ('restricted', '출입금지')], default='danger', max_length=20),
        ),
        migrations.AlterField(
            model_name='zoneevent',
            name='trigger_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
