# Generated by Django 4.2.29 on 2026-04-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=50, unique=True)),
                ("device_name", models.CharField(max_length=100)),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("gas", "가스"),
                            ("power", "전력"),
                            ("temperature", "온도"),
                            ("motion", "동작"),
                        ],
                        default="gas",
                        max_length=20,
                    ),
                ),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("caution", "주의"),
                            ("danger", "위험"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("last_value", models.FloatField(blank=True, null=True)),
                (
                    "last_value_unit",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["device_id"],
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("co", models.FloatField(blank=True, null=True)),
                ("h2s", models.FloatField(blank=True, null=True)),
                ("co2", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("caution", "주의"),
                            ("danger", "위험"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="devices_sen_device__859ff1_idx",
                    )
                ],
            },
        ),
    ]
